# Generated by Django 4.2.17 on 2025-01-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                ("merchant", models.CharField(max_length=100)),
                ("amt", models.FloatField()),
                ("gender", models.CharField(max_length=10)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=50)),
                ("zip", models.IntegerField()),
                ("lat", models.FloatField()),
                ("long", models.FloatField()),
                ("city_pop", models.IntegerField()),
                ("job", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("unix_time", models.BigIntegerField()),
                ("merch_lat", models.FloatField()),
                ("merch_long", models.FloatField()),
                ("is_fraud", models.BooleanField()),
                ("fraud_probability", models.FloatField()),
            ],
        ),
    ]
